version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "docker.io/library/postgres:13.1-alpine"
    environment:
      - POSTGRES_PASSWORD=fx14ef
      - POSTGRES_DB=employees
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db-data: